// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Super_Mega_Desk.Models;

namespace Super_Mega_Desk.Migrations
{
    [DbContext(typeof(Super_Mega_DeskContext))]
    partial class Super_Mega_DeskContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Super_Mega_Desk.Models.Desk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Area");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120);

                    b.Property<string>("Date");

                    b.Property<double>("Depth");

                    b.Property<double>("DrawerNumber");

                    b.Property<double>("FinalCost");

                    b.Property<string>("Material");

                    b.Property<double>("ShippingCost");

                    b.Property<double>("ShippingDays");

                    b.Property<double>("Width");

                    b.HasKey("ID");

                    b.ToTable("Desk");
                });
#pragma warning restore 612, 618
        }
    }
}
